Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DWD_CW_Final.Data;
using DWD_CW_Final.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

public class MessagesController : Controller
{
	private readonly ApplicationDbContext _context;

	public MessagesController(ApplicationDbContext context)
	{
		_context = context;
	}

	public async Task<IActionResult> Index()
	{
		return View(await _context.Messages.Include(m => m.Guest).ToListAsync());
	}

	public IActionResult Add()
	{
		ViewBag.Guests = new SelectList(_context.Guests, "GuestID", "Name");
		return View();
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Add([Bind("GuestID, MessageText, MessageDate")] Message message)
	{
		if (ModelState.IsValid)
		{
			_context.Add(message);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		ViewBag.Guests = new SelectList(_context.Guests, "GuestID", "Name", message.GuestID);
		return View(message);
	}

	public async Task<IActionResult> Delete(int? id)
	{
		if (id == null)
		{
			return NotFound();
		}

		var message = await _context.Messages
			.Include(m => m.Guest)
			.FirstOrDefaultAsync(m => m.MessageID == id);
		if (message == null)
		{
			return NotFound();
		}

		return View(message);
	}

	[HttpPost, ActionName("Delete")]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> DeleteConfirmed(int id)
	{
		var message = await _context.Messages.FindAsync(id);
		_context.Messages.Remove(message);
		await _context.SaveChangesAsync();
		return RedirectToAction(nameof(Index));
	}

	private bool MessageExists(int id)
	{
		return _context.Messages.Any(e => e.MessageID == id);
	}

	// Leave a message
	public IActionResult LeaveMessage()
	{
		return View();
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> LeaveMessage(CreateGuestWithMessageVm vm)
	{
		if (ModelState.IsValid)
		{
			_context.Guests.Add(vm.Guest);
			await _context.SaveChangesAsync();

			vm.Message.GuestID = vm.Guest.GuestID;
			_context.Messages.Add(vm.Message);
			await _context.SaveChangesAsync();

			return RedirectToAction(nameof(Index));
		}
		return View(vm);
	}
}

Views/Shared/Front/Header.cshtml
@using Microsoft.AspNetCore.Identity;
<header id="wn__header" class="header__area sticky__header">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 col-sm-6 col-6 col-lg-2">
				<div class="logo logo-ebook">
					<a asp-route="Home">
						<img src="~/images/logo.png" alt="logo images">
					</a>
				</div>
			</div>
			<div class="col-lg-8 d-none d-lg-block">
				<nav class="mainmenu__nav">
					<ul class="meninmenu d-flex justify-content-start">
						<li class="drop with--one--item">
							<a asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="drop">
							<a asp-controller="Messages" asp-action="LeaveMessage">Leave a Message</a>
						</li>
					</ul>
				</nav>
			</div>


			<div class="col-md-6 col-sm-6 col-6 col-lg-2">
				<ul class="header__sidebar__right d-flex justify-content-end align-items-center">
					<li class="setting__bar__icon">
						<a class="setting__active" href="#"> </a>
						<div class="searchbar__content setting__block">
							<div class="content-inner">

								<div class="switcher-currency">
									<strong class="label switcher-label">
										<span>Admin Login</span>
									</strong>
									<div class="switcher-options">
										<div class="switcher-currency-trigger">
											<div class="setting__menu">
												
												
												@if (User.Identity.IsAuthenticated)
												{
														<span><a asp-action="Index" asp-controller="Dashboard">Admin Dashboard</a></span>
														<span><a onclick="document.getElementById('formLogout').submit();">Sign Out</a></span>
														<form id="formLogout" asp-controller="Account" asp-action="Logout" method="post"></form>
												}
												else
												{
													<span><a asp-controller="Account" asp-action="SignIn">Sign In</a></span>
												}



											</div>
										</div>
									</div>
								</div>


							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="row d-none">
			<div class="col-lg-12 d-none">
				<nav class="mobilemenu__nav">
					<ul class="meninmenu">
						<li><a asp-route="Home">Home</a></li>

						<li><a asp-route="Shop">Shop</a></li>
					</ul>
				</nav>
			</div>
		</div>
		<div class="mobile-menu d-block d-lg-none">
		</div>
	</div>
</header>
<!-- //Header -->

Views/Shared/Front/_Layout.cshtml
@using Microsoft.AspNetCore.Http.Extensions

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Sydenham Library</title>
	<link rel="shortcut icon" href="~/ebook.lk.ico">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,600,600i,700,700i,800" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/line-awesome/css/line-awesome.min.css">
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/plugins.css">
	<link rel="stylesheet" href="~/style.css">


   <link rel="stylesheet" href="~/css/custom.css">
	    <style>
        body::-webkit-scrollbar {
        width: 3px;
        }

        body::-webkit-scrollbar-track {
        background: #f6f6f6;
        }

        body::-webkit-scrollbar-thumb {
        background-color: #2f5a85;
        border-radius: 10px; 
        @* border: 1px solid #fff; *@
        }
    </style>

	<script src="~/js/vendor/modernizr-3.5.0.min.js"></script>


</head>
<body>
    <div class="wrapper" id="wrapper">
        <partial name="~/Views/Shared/Front/Header.cshtml" />
        @RenderBody()

        <!-- Footer Area -->
		<footer id="wn__footer" class="footer__area bg__cat--8 brown--color">
			<div class="copyright__wrapper">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12">
							<div class="copyright">
								<div class="copy__right__inner text-left">
									<p>CW By M S A Azkar</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- //Footer Area -->
    </div>

	<script src="~/js/vendor/jquery-3.2.1.min.js"></script>
	<script src="~/js/popper.min.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/plugins.js"></script>
	<script src="~/js/active.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>