Models/Reservation.cs
namespace DWD_CW_Final.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class Reservation
    {
        [Key]
        public int ReservationID { get; set; }

        public int? GuestID { get; set; }
        public Guest? Guest { get; set; }

        public int? BookID { get; set; }
        public Book? Book { get; set; }

        public int? CDID { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ReservationDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime? IssueDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ReturnDate { get; set; }

        public string? Status { get; set; } = "Reserved"; // Set default status to "Reserved"
    }
}

Models/ReservationViewModel.cs
namespace DWD_CW_Final.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class ReservationViewModel
    {
        [Required]
        [Display(Name = "Guest Name")]
        public string GuestName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Guest Email")]
        public string GuestEmail { get; set; }

        [Display(Name = "Book")]
        public int? BookID { get; set; }

        [Display(Name = "CD")]
        public int? CDID { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Reservation Date")]
        public DateTime ReservationDate { get; set; } = DateTime.Today;
    }
}

Controllers/ReservationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DWD_CW_Final.Data;
using DWD_CW_Final.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

public class ReservationsController : Controller
{
    private readonly ApplicationDbContext _context;

    public ReservationsController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: Reservations
    public async Task<IActionResult> Index()
    {
        var reservations = _context.Reservations
            .Include(r => r.Guest)
            .Include(r => r.Book);
        return View(await reservations.ToListAsync());
    }

    // GET: Reservations/Reserve
    public IActionResult Reserve()
    {
        ViewBag.Books = new SelectList(_context.Books, "BookID", "Title");

        var viewModel = new ReservationViewModel
        {
            ReservationDate = DateTime.Today
        };

        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Reserve([Bind("GuestName, GuestEmail, BookID, CDID, ReservationDate")] ReservationViewModel reservationViewModel)
    {
        if (ModelState.IsValid)
        {
            var guest = new Guest
            {
                Name = reservationViewModel.GuestName,
                Email = reservationViewModel.GuestEmail
            };
            _context.Guests.Add(guest);
            await _context.SaveChangesAsync();

            var reservation = new Reservation
            {
                GuestID = guest.GuestID,
                BookID = reservationViewModel.BookID,
                CDID = reservationViewModel.CDID,
                ReservationDate = reservationViewModel.ReservationDate,
                Status = "Reserved"
            };

            _context.Add(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        ViewBag.Books = new SelectList(_context.Books, "BookID", "Title");
        return View(reservationViewModel);
    }

    // GET: Reservations/Issue/5
    public async Task<IActionResult> Issue(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var reservation = await _context.Reservations
            .Include(r => r.Guest)
            .Include(r => r.Book)
            .FirstOrDefaultAsync(m => m.ReservationID == id);
        if (reservation == null)
        {
            return NotFound();
        }

        var viewModel = new IssueReservationViewModel
        {
            ReservationID = reservation.ReservationID,
            GuestID = reservation.GuestID,
            Guest = reservation.Guest,
            BookID = reservation.BookID,
            Book = reservation.Book,
            CDID = reservation.CDID,
            ReservationDate = reservation.ReservationDate,
            IssueDate = reservation.IssueDate,
            ReturnDate = reservation.ReturnDate,
            Status = reservation.Status
        };

        ViewBag.Guests = new SelectList(_context.Guests, "GuestID", "Name", reservation.GuestID);
        ViewBag.Books = new SelectList(_context.Books, "BookID", "Title", reservation.BookID);

        return View(viewModel);
    }

    // POST: Reservations/Issue/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Issue(int id, [Bind("ReservationID, GuestID, BookID, CDID, ReservationDate, IssueDate, ReturnDate, Status")] IssueReservationViewModel viewModel)
    {
        if (id != viewModel.ReservationID)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                var reservation = await _context.Reservations.FindAsync(viewModel.ReservationID);
                if (reservation == null)
                {
                    return NotFound();
                }

                reservation.IssueDate = viewModel.IssueDate;
                reservation.ReturnDate = viewModel.ReturnDate;
                reservation.Status = viewModel.Status;

                _context.Update(reservation);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ReservationExists(viewModel.ReservationID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        ViewBag.Guests = new SelectList(_context.Guests, "GuestID", "Name", viewModel.GuestID);
        ViewBag.Books = new SelectList(_context.Books, "BookID", "Title", viewModel.BookID);
        return View(viewModel);
    }

    // GET: Reservations/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var reservation = await _context.Reservations.FindAsync(id);
        if (reservation == null)
        {
            return NotFound();
        }

        var viewModel = new EditReservationViewModel
        {
            ReservationID = reservation.ReservationID,
            GuestID = reservation.GuestID,
            Guest = reservation.Guest,
            BookID = reservation.BookID,
            Book = reservation.Book,
            CDID = reservation.CDID,
            ReservationDate = reservation.ReservationDate,
            IssueDate = reservation.IssueDate,
            ReturnDate = reservation.ReturnDate,
            Status = reservation.Status
        };

        ViewBag.Guests = new SelectList(_context.Guests, "GuestID", "Name", reservation.GuestID);
        ViewBag.Books = new SelectList(_context.Books, "BookID", "Title", reservation.BookID);
        return View(viewModel);
    }

    // POST: Reservations/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("ReservationID, GuestID, BookID, CDID, ReservationDate, IssueDate, ReturnDate, Status")] EditReservationViewModel viewModel)
    {
        if (id != viewModel.ReservationID)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                var reservation = await _context.Reservations.FindAsync(viewModel.ReservationID);
                if (reservation == null)
                {
                    return NotFound();
                }

                reservation.ReservationDate = viewModel.ReservationDate;
                reservation.IssueDate = viewModel.IssueDate;
                reservation.ReturnDate = viewModel.ReturnDate;
                reservation.Status = viewModel.Status;

                _context.Update(reservation);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ReservationExists(viewModel.ReservationID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        ViewBag.Guests = new SelectList(_context.Guests, "GuestID", "Name", viewModel.GuestID);
        ViewBag.Books = new SelectList(_context.Books, "BookID", "Title", viewModel.BookID);
        return View(viewModel);
    }



    // GET: Reservations/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var reservation = await _context.Reservations
            .Include(r => r.Guest)
            .Include(r => r.Book)
            .FirstOrDefaultAsync(m => m.ReservationID == id);
        if (reservation == null)
        {
            return NotFound();
        }

        return View(reservation);
    }

    // POST: Reservations/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var reservation = await _context.Reservations.FindAsync(id);
        _context.Reservations.Remove(reservation);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    // GET: Reservations/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var reservation = await _context.Reservations
            .Include(r => r.Guest)
            .Include(r => r.Book)
            .FirstOrDefaultAsync(m => m.ReservationID == id);
        if (reservation == null)
        {
            return NotFound();
        }

        return View(reservation);
    }

    private bool ReservationExists(int id)
    {
        return _context.Reservations.Any(e => e.ReservationID == id);
    }
}

Views/Reservations/Delete.cshtml
@model DWD_CW_Final.Models.Reservation

<h1>Delete Reservation</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Guest
        </dt>
        <dd class="col-sm-10">
            @Model.Guest.Name
        </dd>
        <dt class="col-sm-2">
            Book
        </dt>
        <dd class="col-sm-10">
            @Model.Book?.Title
        </dd>
        <dt class="col-sm-2">
            Reservation Date
        </dt>
        <dd class="col-sm-10">
            @Model.ReservationDate
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="ReservationID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

Views/Reservations/Details.cshtml
@model DWD_CW_Final.Models.Reservation

@{
    ViewData["Title"] = "Manage Reservations";
    Layout = "~/Views/Shared/Admin/_Layout.cshtml";
}


<h1>Reservation Details</h1>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Guest
        </dt>
        <dd class="col-sm-10">
            @Model.Guest.Name
        </dd>
        <dt class="col-sm-2">
            Book
        </dt>
        <dd class="col-sm-10">
            @Model.Book?.Title
        </dd>
        <dt class="col-sm-2">
            Reservation Date
        </dt>
        <dd class="col-sm-10">
            @Model.ReservationDate
        </dd>
        <dt class="col-sm-2">
            Issue Date
        </dt>
        <dd class="col-sm-10">
            @Model.IssueDate
        </dd>
        <dt class="col-sm-2">
            Return Date
        </dt>
        <dd class="col-sm-10">
            @Model.ReturnDate
        </dd>
        <dt class="col-sm-2">
            Status
        </dt>
        <dd class="col-sm-10">
            @Model.Status
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ReservationID" class="btn btn-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Views/Reservations/Edit.cshtml
@model DWD_CW_Final.Models.EditReservationViewModel

@{
    ViewData["Title"] = "Manage Reservations";
    Layout = "~/Views/Shared/Admin/_Layout.cshtml";
}


<h1>Edit Reservation</h1>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="ReservationID" />
    <input type="hidden" asp-for="GuestID" />
    <input type="hidden" asp-for="BookID" />
    <input type="hidden" asp-for="CDID" />

    <div class="form-group">
        <label asp-for="GuestID" class="control-label"></label>
        <select asp-for="GuestID" class="form-control" asp-items="ViewBag.Guests" disabled></select>
        <span asp-validation-for="GuestID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BookID" class="control-label"></label>
        <select asp-for="BookID" class="form-control" asp-items="ViewBag.Books" disabled></select>
        <span asp-validation-for="BookID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CDID" class="control-label"></label>
        <select asp-for="CDID" class="form-control" asp-items="ViewBag.CDs" disabled></select>
        <span asp-validation-for="CDID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ReservationDate" class="control-label"></label>
        <input asp-for="ReservationDate" class="form-control" />
        <span asp-validation-for="ReservationDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IssueDate" class="control-label"></label>
        <input asp-for="IssueDate" class="form-control" />
        <span asp-validation-for="IssueDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ReturnDate" class="control-label"></label>
        <input asp-for="ReturnDate" class="form-control" />
        <span asp-validation-for="ReturnDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Status" class="control-label"></label>
        <select asp-for="Status" class="form-control">
            <option value="Reserved">Reserved</option>
            <option value="Issued">Issued</option>
            <option value="Returned">Returned</option>
            <option value="Cancelled">Cancelled</option>
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

Views/Reservations/Index.cshtml
@model IEnumerable<DWD_CW_Final.Models.Reservation>

@{
    ViewData["Title"] = "Manage Reservations";
    Layout = "~/Views/Shared/Admin/_Layout.cshtml";
}


<h1>Reservations</h1>

<p>
    <a href="@Url.Action("Reserve", "Reservations")" class="btn btn-primary">Add Reservation</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Guest</th>
            <th>Book/CD</th>
            <th>Reservation Date</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var reservation in Model)
        {
            <tr>
                <td>@reservation.Guest.Name</td>
                <td>@reservation.Book?.Title</td>
                <td>@reservation.ReservationDate</td>
                <td>@reservation.Status</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@reservation.ReservationID" class="btn btn-warning">Edit</a> |
                    <a asp-action="Details" asp-route-id="@reservation.ReservationID" class="btn btn-info">Details</a> |
                    <a asp-action="Delete" asp-route-id="@reservation.ReservationID" class="btn btn-danger">Delete</a>
                    <a asp-action="Issue" asp-route-id="@reservation.ReservationID" class="btn btn-primary">Issue</a>

                </td>
            </tr>
        }
    </tbody>
</table>

Views/Reservations/Issue.cshtml
@model DWD_CW_Final.Models.IssueReservationViewModel

@{
    ViewData["Title"] = "Manage Reservations";
    Layout = "~/Views/Shared/Admin/_Layout.cshtml";
}


<h1>Issue a Book/CD</h1>

<form asp-action="Issue" method="post">
    <input type="hidden" asp-for="ReservationID" />
    <input type="hidden" asp-for="GuestID" />
    <input type="hidden" asp-for="BookID" />
    <input type="hidden" asp-for="CDID" />

    <div class="form-group">
        <label asp-for="GuestID" class="control-label"></label>
        <select asp-for="GuestID" class="form-control" asp-items="ViewBag.Guests" disabled></select>
        <span asp-validation-for="GuestID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BookID" class="control-label"></label>
        <select asp-for="BookID" class="form-control" asp-items="ViewBag.Books" disabled></select>
        <span asp-validation-for="BookID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CDID" class="control-label"></label>
        <select asp-for="CDID" class="form-control" asp-items="ViewBag.CDs" disabled></select>
        <span asp-validation-for="CDID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ReservationDate" class="control-label"></label>
        <input asp-for="ReservationDate" class="form-control" disabled />
        <span asp-validation-for="ReservationDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IssueDate" class="control-label"></label>
        <input asp-for="IssueDate" class="form-control" />
        <span asp-validation-for="IssueDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ReturnDate" class="control-label"></label>
        <input asp-for="ReturnDate" class="form-control" />
        <span asp-validation-for="ReturnDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Status" class="control-label"></label>
        <select asp-for="Status" class="form-control">
            <option value="Reserved">Reserved</option>
            <option value="Issued">Issued</option>
            <option value="Returned">Returned</option>
            <option value="Cancelled">Cancelled</option>
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Issue" class="btn btn-primary" />
    </div>
</form>

Views/Reservations/Reserve.cshtml
@model DWD_CW_Final.Models.ReservationViewModel

<h1>Reserve a Book/CD</h1>

<form asp-action="Reserve" method="post">
    <div class="form-group">
        <label asp-for="GuestName" class="control-label"></label>
        <input asp-for="GuestName" class="form-control" />
        <span asp-validation-for="GuestName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GuestEmail" class="control-label"></label>
        <input asp-for="GuestEmail" class="form-control" />
        <span asp-validation-for="GuestEmail" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BookID" class="control-label"></label>
        <select asp-for="BookID" class="form-control" asp-items="ViewBag.Books"></select>
        <span asp-validation-for="BookID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CDID" class="control-label"></label>
        <select asp-for="CDID" class="form-control" asp-items="ViewBag.CDs"></select>
        <span asp-validation-for="CDID" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="ReservationDate" class="form-control" />
    <div class="form-group">
        <input type="submit" value="Reserve" class="btn btn-primary" />
    </div>
</form>